/*
 (c) Skimlinks 2009-2018
 Build time: Wed, 08 Aug 2018 15:56:42 GMT
 Version: 13.7.1
*/
(function(){function Bc(a){xa(a,"BEACON_CALLBACK__AUX")}function Cc(a){xa(a,"BEACON_CALLBACK__POST_PAGE_LOAD")}function Dc(a){xa(a,"BEACON_CALLBACK__PRE_PAGE_LOAD")}function Ec(a){var b=void 0,c=void 0,d=void 0,e=void 0,k=void 0;c=a;b=e=null;k=5;c.Limit&&(k=c.Limit);d=function(){return c.Priority||0};return{group_id:function(){return e?e.id():0},dec_limit:function(){return k-1},limit:function(){return k},action_type:function(){return c.ActionType},text:function(){return c.OriginalPhrase},start_byte:function(){return c.StartByte},
url:function(){return c.Url},multi:function(){return c.Mt?!0:!1},is_editor:function(){return null!=c.ValidOn&&""!==c.ValidOn?!0:!1},group_priority:function(){return e?e.group_priority():d()},id:function(){return b?b:c.PhraseId},groups:function(){var a;return(a=c.Groups)?a:[]},title:function(){return c.Unlinked?"":null!=c.ActionTitle?c.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(a){c.Title=c.Unlinked?"":a},occurrence:function(){return c.PhraseOccurrence},set_group:function(a){return e=
a},set_id:function(a){return b=a}}}function Fc(){var a=u.linksImpressions;a={phr:a.skimwords.urls,unl:a.unlinked.urls,slc:a.skimlinks.count,swc:a.skimwords.count,ulc:a.unlinked.count,jsl:(new Date).getTime()-u.loading_started,pref:h.referrer,uc:ia,t:1,jsf:""};return Ya(a)}function Za(a){w(a,function(a){void 0===m.aff_domains[a]&&(m.aff_domains[a]=null)});return ya(a,"skimlinksBeaconAuxCallback")}function $a(a,b){return 0===b.length?!1:ja(a,b.join(","))?!0:a.parentNode?$a(a.parentNode,b):!1}function ab(a,
b){var c=a.style.cssText;""!==c&&(c+=" ");var d=f("link_background");d&&(-1===d.indexOf("#")&&(d="#"+d),c+="background-color: "+d+" !important; ");null!==f("link_tooltip",null)&&(a.title=f("link_tooltip"));b&&(za&&(d=za,-1===d.indexOf("#")&&(d="#"+d),c+="color: "+d+" !important; "),Aa&&(c+="font-weight: "+Aa+" !important; "),Q&&(c="double"===Q?c+"border-bottom: 1px double !important; ":"dashed"===Q?c+"border-bottom: 1px dashed !important; ":c+("text-decoration: "+Q+" !important; ")),Ba&&(c+="font-style: "+
Ba+" !important; "),f("skimwords_link_style")&&(d=f("skimwords_link_style"),c+=d+"; "),f("skimwords_link_class")&&(a.className=y(a.className+" "+f("skimwords_link_class"))),Ca&&(a.title=Ca),null===a.getAttribute("title")&&(a.title="Shopping link added by SkimWords"),a.getAttribute("data-skim-creative")&&(d=parseInt(a.getAttribute("data-skim-creative"),10)%10,1===d||2===d))&&(a.title="");a.style.cssText=c;return!0}function ka(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:p,c=null;
a&&(c=new RegExp("\\b"+bb(a)+"\\b","i"));var d=Da(b.getElementsByTagName("a"));b=Da(b.getElementsByTagName("area"));d=d.concat(b);return I(d,function(a,b){b.href&&(!c||b.className&&c.test(b.className))&&a.push(b);return a},[])}function cb(a){return-1===a.indexOf("#slm-")||(a=a.split("#slm-"),2!==a.length||isNaN(a[1])||10*parseInt(a[1],10)!==10*a[1])?null:parseInt(a[1],10)}function la(a,b){b=b||ma(a);if(!b)return!0;db(b);var c=f("skimlinks_keywee_pixel",null);var d=v(l.location.href,"utm_campaign=fbkw");
c&&d&&na(c);f("vglnk")&&A(b,"skimwords-link")&&(a&&a.stopPropagation?a.stopPropagation():(c=l.event,c.cancelBubble=!0));return!0}function db(a,b){a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=eb(a));if(a){var c=fb(a);var d=m.waypointDomain;if(c.length>=d.length&&c.substr(0,d.length)===d)return!0;d=-1!==c.indexOf(d)?c:gb(a,c);if(R){var e=f("pageTracker");var k="/"+R+"/"+c;null!=e&&e._trackPageview?e._trackPageview(k):f("_gaq")?(e=f("_gaq"),e.push(["_trackEvent",
R,"click",c])):f("ga")&&f("ga")("send","event","click",R,c)}hb(a,d,b)}return!0}function J(a,b,c){for(null==c&&(c=!1);null!=a&&a!==m.html_root;){var d=A(a,b)||A(a,"noskim");if(a.className&&d)return!0;a=c?null:a.parentNode}return!1}function ib(a){var b=void 0;null!==m.exclude_lookup&&null!==m.include_lookup||Ea();if(!a)return!1;var c=m.exclude_lookup;for(b in c)if(jb.call(c,b)){var d=c[b];if(0===b.indexOf("*")){b=b.substr(1);--d;var e=a.lastIndexOf(b);if(-1!==e&&e===a.length-d)return!0}else if(a===
b)return!0}return!1}function Fa(a,b){var c;if(c=f("_merchantSettings"))c=-1!==b.indexOf("itunes.apple.com")||-1!==b.indexOf("itunes.com")||-1!==b.indexOf("phobos.apple.com");return c||ib(b)?!1:kb(a)&&lb(b)}function mb(a){for(var b,c,d,e,k;a&&a!==m.html_root;){d=a.id;c=0;for(e=S.length;c<e;c++)if(b=S[c],A(a,b))return!1;k=m.included_ids;c=0;for(e=k.length;c<e;c++)if(b=k[c],d===b)return!1;e=m.excluded_classes;d=0;for(c=e.length;d<c;d++)if(b=e[d],A(a,b))return!0;a=a.parentNode}return S.length||m.included_ids.length?
!0:!1}function eb(a){for(;a.parentNode;){a=a.parentNode;var b=a.nodeName.toUpperCase();if("A"===b||"AREA"===b)return a}return null}function H(a){return a.replace(/^www\./i,"")}function Gc(){for(var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],b=arguments[1],c=arguments[2],d=0;d<a.length;d++){var e=nb(a[d]);if(!K(e))return n(c)?c(e,b):e}return b}function nb(a,b,c){return K(l[a])?b:n(c)?c(l[a],b):l[a]}function f(a,b,c){return T(a)?Gc(a,b,c):nb(a,b,c)}function T(a){return Array.isArray?
Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function C(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function w(a,b){if(T(a))for(var c=0;c<a.length;c++)b(a[c],c,a);else for(c in a)C(a,c)&&b(a[c],c,a)}function K(a){return"undefined"===typeof a||null===a}function n(a){return"[object Function]"===Object.prototype.toString.call(a)}function Ga(a,b){if(n(a.indexOf))return a.indexOf(b);if(T(a))for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1}function Hc(){var a=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:"";return 0===Ga((0<arguments.length&&void 0!==arguments[0]?arguments[0]:"").slice(2<arguments.length&&void 0!==arguments[2]?arguments[2]:0),a)}function ob(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"",b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"",c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0;c=c<a.length?c|0:a.length;return a.substr(c-b.length,b.length)===b}function I(a,b,c){for(var d=0,e=null===
a?0:a.length;d<e;)c=b(c,a[d],d,a),d+=1;return c}function oa(a){return"boolean"===typeof a}function y(a){return K(a)?"":a.toString().replace(/^[\s\xA0]+|[\s\xA0]+$/g,"")}function x(a){return l.encodeURIComponent(a).replace(/[!'()*~]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function pb(a){return x(a).replace(/%20/g,"+")}function pa(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,c=p.createElement("a");c.href=b?a:Ic(a);try{return H(c.hostname)}catch(d){return""}}
function Ic(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"http",c="";/^https?:\/\//.test(a)||/^\/[^/]+/.test(a)||(c=/^\/\//.test(a)?b+":":b+"://");return""+c+a}function kb(a){var b=pa(a,1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0),c=m.hostname,d=ob(b,"."+c)||ob(c,"."+b);return b!==c&&!d}function qb(a){a=a.replace(/^\??/,"").split("&");return I(a,function(a,c){if(!c)return a;var b=c.split(/=/),e=b[0];if(1===b.length)return a[e]=!0,a;a[e]=decodeURIComponent(b.splice(1).join(""));
return a},{})}function rb(a){var b=qb(l.location.search);return C(b,a)}function U(a,b){var c=[];b=b||x;w(a,function(a,e){c.push(e+"="+b(a))});return c.join("&")}function sb(){var a={};L&&(a.dnt=L);V&&(a.fdnt=1);return a}function v(a,b){return-1<Ga(a,b)}function tb(a){return Ha?Ha:"msie"===h.detect.browser&&8>=h.detect.version||a?"//go.redirectingat.com":"//go.skimresources.com"}function qa(a){return v(m.waypointDomain,a)||v(a,"go.redirectingat.com")||v(a,"go.skimresources.com")}function W(a){if(K(a))return[];
var b=[],c;for(c in a)C(a,c)&&b.push(c);return b}function Jc(a,b){return I(W(b),function(c,d){var e=a[d]===b[d];return c&&e},!0)}function ra(a){var b=!1,c=void 0;return function(){if(b)return c;c=a.apply(this,arguments);b=!0;return c}}function ub(a,b){var c=[];w(a,function(d,e){b(d,e,a)&&c.push(d)});return c}function Kc(){return ub(0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],function(a){return!!a})}function Lc(a,b){var c=!1,d=void 0;return function(){if(c)return d;setTimeout(function(){c=
!1},b);c=!0;return d=a.apply(this,arguments)}}function Ia(a,b,c){var d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:!1;a&&(a.nodeName||a===l)&&(p.addEventListener?a.addEventListener(b,c,d):a.attachEvent("on"+b,function(){return 7>h.detect.version&&!l.event?(setTimeout(function(){return c.call(a,l.event)},100),!0):c.call(a,l.event)}))}function Ja(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:[],c=arguments[3];if(a){var d=Lc(arguments[2],200);w(b,function(b){try{Ia(a,b,d,
c)}catch(k){}})}}function ma(a){var b=void 0;a=a.target||a.srcElement||a.originalTarget;var c=null!=a?null!=(b=a.nodeName)?"function"===typeof b.toUpperCase?b.toUpperCase():void 0:void 0:void 0;"A"!==c&&"AREA"!==c&&(a=eb(a));return a}function q(a,b,c){3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{var d=a[b];d||(d=a.getAttribute(b));return d}catch(e){return null}}function Mc(a,b){b=b||vb;a.skimlinksOriginalHostname=a.hostname;a.skimlinksOriginalHref=a.href;
setTimeout(function(){a.href=a.skimlinksOriginalHref;delete a.skimlinksOriginalHostname;delete a.skimlinksOriginalHref},b)}function hb(a,b,c){if(a){"string"===typeof a.skimlinksOriginalHref||Mc(a,c);c=null;var d=a.childNodes.length&&3===a.childNodes[0].nodeType;"msie"===h.detect.browser&&d&&(c=a.innerHTML);a.href=b;c&&c!==a.innerHTML&&(a.innerHTML=c)}}function wb(a,b){var c=b?b.charAt(0).toUpperCase()+b.slice(1):"";return a["skimlinksOriginal"+c]||a[b]}function xb(a,b){var c=2<arguments.length&&void 0!==
arguments[2]?arguments[2]:!1,d=document.createElement("div"),e="qsa"+String(Math.random()).slice(3);d.innerHTML="x<style>"+b+"{qsa:"+e+";}";d=yb.appendChild(d.lastChild);e=zb(a,b,c,e);yb.removeChild(d);return c?e[0]:e}function zb(a,b,c,d){var e=/1|9/.test(a.nodeType),k=a.childNodes,g=[],X=0;if(e&&a.currentStyle&&a.currentStyle.qsa===d&&g.push(a)&&c)return g;for(;(a=k[X])&&(g=g.concat(zb(a,b,c,d)),X+=1,!c||!g.length););return g}function Da(a){return I(a,function(a,c){return a.concat(c)},[])}function Nc(a,
b){1===arguments.length&&"string"===typeof a&&(b=a,a=p);return n(a.querySelectorAll)?Da(a.querySelectorAll(b)):xb(a,b,!1)}function A(a,b){return a&&a.className&&b?0<=Ga(y(a.className).split(/\s+/),b):!1}function Ka(a){var b;(b=mb(a))||(b=q(a,"rel"),b=!(Y?Y===b:!b||!La(b)));if(b)return"IGNORE";if(b=Ab)null===a.offsetParent?b=!0:(b=l.getComputedStyle,b=n(b)?"hidden"===b(a).visibility:!1);if(b)return"IGNORE";b=y(wb(a,"href"));a=H(wb(a,"hostname"));var c=b?/^https?:\/\//.test(b)||/^\/\//.test(b):!1;if(c&&
Fa(b,a)){if(!0===m.aff_domains[a]||C(Ma,a))return"AFFILIATE";if(qa(a))return"PRE_AFFILIATED";if(Na&&!C(m.aff_domains,a))return"UNKNOWN";if(kb(b)&&!ib(a))return""===h.cookie&&Bb?"AFFILIATE":"TRACK"}return"IGNORE"}function B(){var a=arguments[0],b=Array.prototype.slice.call(arguments,1);K(a)&&(a={});w(b,function(b){K(b)&&(b={});w(W(b),function(c){a[c]=b[c]})});return a}function Cb(a,b){var c=B({},Oc,b||{}),d=document.createElement("script");d.type="text/javascript";d.async=c.async;d.onerror=c.onError;
d.onload=c.onLoad;d.src=a;document.head.appendChild(d);return d}function Oa(a){return Db()[a]}function Pc(a,b,c){Pa(a)&&Eb[a]===b?c(Oa(a)):Cb(b,{onLoad:function(){Pa(a)&&(Eb[a]=b,c(Oa(a)))}})}function Pa(a){var b=Db();return C(b,a)}function Db(){Z.__SKIM_JS_GLOBAL__||(Z.__SKIM_JS_GLOBAL__={});Z.__SKIM_JS_GLOBAL__.modules||(Z.__SKIM_JS_GLOBAL__.modules={});return Z.__SKIM_JS_GLOBAL__.modules}function Qc(a){a.width=0;a.height=0;a.style.display="none"}function Fb(){return(0<arguments.length&&void 0!==
arguments[0]?arguments[0]:p).getElementsByTagName("body")[0]}function na(a,b){M||(M=p.createElement("iframe"),Fb().appendChild(M),Qc(M));var c=M.contentDocument||M.contentWindow.document,d=Fb(c);d||(d=p.createElement("body"),c.appendChild(d));c=c.createElement("img");c.src=a;c.width=1;c.height=1;b&&n(b)&&(c.onload=function(){b()},c.onerror=function(){b()});d.appendChild(c)}function Gb(a){var b=a.href;b=h.cookie?b.replace(/([&?])xguid=([a-fA-F0-9]{32})/,"$1xguid="+h.cookie):b.replace(/([&?]xguid=[a-fA-F0-9]{32})/,
"");b!==a.href&&hb(a,b);return b}function Hb(){var a=sb();sa&&(a.xrf=1);return a}function Rc(){var a=Kc([!!Ib&&"mouseup","click"]);Ja(p,a,function(a){var b=ma(a),d=0===a.button;if(b&&d){d=Ka(b);var e=ta().moduleName;Jb()&&(d===z.AFFILIATE||d===z.PRE_AFFILIATED)&&Pa(e)||Kb(a,b,d)}},!0)}function Sc(){Ja(p,["auxclick","contextmenu","touchstart"],function(a){if(a=ma(a)){var b=Ka(a);b===z.AFFILIATE||b===z.UNKNOWN?db(a,200):b===z.PRE_AFFILIATED&&Gb(a)}},!0)}function Kb(a,b,c){c===z.AFFILIATE||c===z.UNKNOWN?
(Lb(b),aa&&q(b,"target",aa),c=(c=q(b,"onclick"))&&v(c.toString(),"return false")?!0:(c=b.onclick)&&n(c)&&v(c.toString(),".preventDefault()")?!0:!1,c?(la(a,b),(aa?l.open(b.href,aa):l.open(b.href,"_blank")).focus()):la(a,b)):c===z.PRE_AFFILIATED?Gb(b):c===z.TRACK&&(a=b.href,b={slmcid:cb(a)||"",pubcode:N,referrer:l.location.toString(),pref:h.referrer,site:""+D,url:a,custom:q(b,"data-skimlinks-tracking")||ia||"",xtz:h.timezone,uuid:h.uuid,product:"1"},b=x(JSON.stringify(b)),a=B({call:"track",rnd:Math.random()},
Hb()),b=U(a)+"&data="+b,na("//t.skimresources.com/api/?"+b))}function Tc(a){var b=q(a,"rel"),c=H(a.hostname);!b&&c&&!0===m.aff_domains[c]&&q(a,"rel","nofollow")}function Uc(){Mb&&w(ka(),Tc)}function Vc(){Rc();Sc()}function Nb(a){var b;return a&&-1!==a.indexOf("class=")&&(b=a.match(/([^[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a}function ya(a,b){var c=!a||!a.length;E.called&&c?(E.pendingRequests+=1,l[b]()):(c=B({callback:b},{data:JSON.stringify({pubcode:N,page:l.location.href,domains:a})},
sb()),c="//r.skimresources.com/api/?"+U(c),c.length>("msie"===h.detect.browser?2E3:8E3)?ya(a.slice(0,-1),b):(E.called=!0,E.pendingRequests+=1,Cb(c)))}function Ob(a,b,c,d){b=b||{};c=c||function(){};var e=d=d||{};d=e.method;var k=e.data;e=e.headers;var g=new XMLHttpRequest;b=U(b);b.length&&(a=a+"?"+b);g.open(d,a);Wc(g,e);g.onload=function(){if(200===g.status)try{var a=JSON.parse(g.responseText);c(a)}catch(O){c(g.responseText)}};g.send(k)}function Wc(a,b){w(b,function(b,d){a.setRequestHeader(d,b)})}
function Ya(a){a={data:JSON.stringify(B({pag:l.location.href,guid:h.cookie,uuid:h.uuid,tz:h.timezone,sessid:h.sessid,pub:N,slmcid:u.campaign_ids},a))};return a=B(a,Hb())}function Pb(a){0!==u.awaitedModules.length&&(u.awaitedModules=ub(u.awaitedModules,function(b){return b!==a}),0===u.awaitedModules.length&&Qb.post("//t.skimresources.com/api/track.php",null,null,{headers:{"Content-type":"application/x-www-form-urlencoded"},data:U(Fc(),pb)}))}function Xc(a){a=a.match.phrase;return{w:a.text(),lp:a.url(),
t:ua.creative}}function Qa(a){a=a||[];var b=I(a,function(a,b,e){a[e]=b;return a},{});u.linksImpressions.unlinked={count:a.length,urls:b};Pb("unlinked")}function Ra(a){return String(a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function Yc(){var a=Zc.settings;2===a.nc?h.unlinkedEnabled&&Za(m.domain_data.domains):h.unlinkedEnabled&&(a.includes?(F&&F.length&&(a.excludes=a.excludes.concat(F)),G.traverse(a.includes,a.excludes,a.read_onlys)):F&&F.length?G.traverse(["body"],
F,[]):G.traverse(["body"],[],[]));Rb()}function Rb(){a:{var a=p.getElementsByTagName("body");if(a.length){a=a[0].textContent||a[0].innerText;var b;if(b=a)a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi.exec(a),b=a.length&&""!==a[0]?!0:!1;if(b){a=!0;break a}}a=!1}a?(h.skimwordsEnabled||G.traverse([],F,[]),Sb()):Qa()}function Sb(){var a=void 0;var b;var c=G.get_as_hash_node_dict();var d={};for(a in c){var e=c[a];if(e.parentNode&&!(mb(e)||J(e,"noskimwords")||
J(e,"noskimlinks")||J(e,"noskimw")||e.meta&&e.meta.ReadOnly)){e=Tb(e,a);var k=e[0];var g=0;for(b=k.length;g<b;g++)e=k[g],!d[e]&&Ub(e)&&(d[e]=!0,m.domain_data.domains.push(e))}}a=W(d);a.length?Za(a):Qa()}function $c(){var a=[];W(m.aff_domains).length&&(w(ua.url_spans,function(b){m.aff_domains[b.match.domain]&&(Vb(b.node,b.match,!0),a.push(Xc(b)))}),setTimeout(function(){var a;var c=ka("skimlinks-unlinked");var d=[];var e=0;for(a=c.length;e<a;e++){var k=c[e];d.push(Wb(k))}return d},10));Qa(a)}function ad(a,
b,c){var d=document.createElement(a);w(b||{},function(a,b){var c=b.split(".");var e=d;if(e&&c&&c.length)for(var k=c.length,h=e,f=null,m=0;m<k;m++){var l=c[m];if(m===k-1){try{e[l]=a}catch(Kd){h[f]={},h[f][l]=a}break}l in e||(e[l]={});h=e;f=l;e=e[l]}});"STYLE"===d.tagName&&(d.type="text/css");"SCRIPT"===d.tagName&&(d.type="text/javascript");Xb(d,[].concat(c||[]));return d}function Xb(a,b){w(b,function(b){if(T(b))Xb(a,b);else{var c="string"===typeof b;"STYLE"===a.tagName&&c&&a.styleSheet?a.styleSheet.cssText+=
b:(c&&(b=document.createTextNode(b)),a.appendChild(b))}})}function bd(a){a&&(a.preventDefault&&n(a.preventDefault)?a.preventDefault():a.returnValue=!1)}function Yb(a,b,c,d,e){d=((d||0)/1E3).toFixed(2);b={typ:"consent",consent:a,publisher_domain_id:parseInt(cd,10),publisher_id:parseInt(dd,10),decision_time:parseFloat(d),test_case:ta().id,page_url:b,destination_url:c};b=JSON.stringify(b);Zb.setItem("skimCONSENT",a);na("//t.skimresources.com/api/consent?data="+x(b),e)}function ed(a,b,c){var d=ta().moduleName;
if(d=Oa(d)){bd(a);var e=h.pageLocation,k=y(b.href),g=Date.now(),X="_blank"===b.target,f=ad("a",{href:k,target:X?"_blank":"_top",rel:b.rel,onclick:function(a){h.skimlinksEnabled&&Kb(a,f,c)}}),l=ra(function(a){var b=Date.now()-g;if(X)Yb(a,e,k,b,function(){}),f.click();else{var c=ra(function(){f.click()});Yb(a,e,k,b,c);setTimeout(c,1E3)}});new d({anchorClone:f,publisherDomain:H(m.hostname),merchantDomain:pa(k),onResolve:function(){return l(!0)},onReject:function(){return l(!1)}})}}function fd(){Ja(p,
["click"],function(a){var b=ma(a),c=0===a.button;b&&c&&(c=Ka(b),c!==z.AFFILIATE&&c!==z.PRE_AFFILIATED||ed(a,b,c))},!0)}function gd(){a:{var a=m;var b=["domain_data","domains"];if(a&&b&&b.length)for(var c=b.length,d=0;d<c;d++){var e=b[d];if(a&&e in a)a=a[e];else{a=void 0;break a}}else a=void 0}a&&Qb.post("//t.skimresources.com/api/link",null,null,{headers:{"Content-type":"application/x-www-form-urlencoded"},data:U(Ya({dl:u.linksImpressions.skimlinks.urls,hae:u.linksImpressions.skimlinks.count?1:0,
typ:"l"}),pb)})}function hd(){return I(ka(),function(a,b){var c=y(b.href),d=H(b.hostname),e;if(!(e=!(!A(b,"skimwords-link")&&!A(b,"skimlinks-unlinked"))||!Fa(c,d)))if(b)if(e=$b.join(", ")){b:{var k=b;if(n(window.Element.prototype.closest))e=k.closest(e);else{for(;k&&1===k.nodeType;){var g=k;var h=e,f=window.Element.prototype;f=f.matches||f.msMatchesSelector||f.mozMatchesSelector||f.webkitMatchesSelector;if(n(f))g=f.call(g,h);else{h=Nc(g.document||g.ownerDocument,h);for(f=0;h[f]&&h[f]!==g;)f+=1;g=
!!h[f]}if(g){e=k;break b}k=k.parentNode}e=null}}e=!!e}else e=!1;else e=!1;if(e)return a;e=a.urls[c];e||(sa?(Sa(d)&&(m.handlers+=1),d=!1):d=Sa(d),e={count:0,ae:d?1:0});e.count++;if(d=cb(c))e.slmcid=d;d=e;1===d.ae&&a.count++;d.slmcid&&(e=d.slmcid,v(u.campaign_ids,e)||u.campaign_ids.push(e));a.urls[c]=d;return a},{urls:{},count:0})}function ac(a){a=a||0;bc&&(0!==E.pendingRequests&&5>a?setTimeout(function(){ac(a+1)},400*a):(u.linksImpressions.skimlinks=hd(),Pb("main-tracking"),gd()))}function id(){ac(0)}
function cc(a,b){P||1E3<b?n(a)&&(P?Ta?a(!0):a(!1):a(!1)):setTimeout(cc,b*=2,a,b)}function dc(){P||(ba.complete&&ca.complete&&(P=!0),P&&"0"!=ba.width&&"0"==ca.width&&(Ta=!0))}function jd(a,b){1===arguments.length&&"string"===typeof a&&(b=a,a=p);return n(a.querySelector)?a.querySelector(b):xb(a,b,!0)}function kd(a,b){if(!a)return[];if(!b)return[].concat(a);var c=[];w(a,function(d,e){c.push(b(d,e,a))});return c}function ld(){var a=!!(window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest);try{JSON.stringify({});
var b=!0}catch(c){b=!1}return b&&a}function md(a){function b(a){return a.toLowerCase().replace(/^\/\/|^https?:\/\//,"")}var c=kd(ec,b);return v(c,b(a))}function nd(){return{skimOptions:od,runTimeInfo:B({},{aff_domains:m.aff_domains},h)}}function pd(a){a=a||[];w(m.aff_domains,function(b,c){if(!0!==b){var d=v(a,c)&&!qa(c);m.aff_domains[c]=d}})}function xa(a,b){--E.pendingRequests;a&&(m.beacon.push(a),t.publish("beacon",a),fc+=1);a=a||{};var c=h,d=a,e=h.cookie,k=h.sessid,g={};d.consent&&(g.consent=d.consent);
if(d.country){g.country=d.country.toUpperCase();var f=rb("skimlinks_locale"),O=qb(l.location.search).skimlinks_locale;f=f&&O.length?O:(f=d.country)?qd[f.toUpperCase()]||"en":"en";g.locale=f}d.guid&&""===e&&(g.cookie=d.guid);d.sessid&&""===k&&(g.sessid=d.sessid);!oa(h.consent)&&"consent"in d&&(g.consent=d.consent);B(c,g);m.waypointDomain=tb(h.cookie);pd(a.merchant_domains);t.publish("EVENTS__BEACON_CALLBACK",{type:b,data:a,isFirstCall:1===fc})}function gc(a){var b;var c=ka();var d=[];var e=0;for(b=
c.length;e<b;e++){var k=c[e];var g=H(k.hostname);var f=y(k.href);k=q(k,"rel");!g||!Fa(f,g)||(Y?Y!==k:k&&La(k))||qa(g)||void 0!==m.aff_domains[g]||(d.push(g),m.domain_data.domains.push(g),m.aff_domains[g]=null)}ya(d,a)}function da(){gc("skimlinksBeaconSecondaryCallback");document.removeEventListener("DOMContentLoaded",da);document.removeEventListener("load",da)}var hc=window.skimlinks_context_window||null,l=hc?window[hc]:window,p=l.document,Ua=f("noskim",!1),rd=
f("noskimlinks",!1),sd=f("noskimwords",!0),td=f("nounlinked",!1),ud=f("skimwords_standard",false),vd=f("skimwords_lite",false),wd=f("skimwords_diy",false),xd=f("skimwords_diy_filter",false),ic=!Ua&&!rd,jc=!Ua&&!sd,kc=!Ua&&!td,L=f("skimlinks_dnt",0,function(a){return a&&"0"!==a&&"false"!==a?1:0}),V=f("skimlinks_nocookie",!1),S=f("skimlinks_included_classes",[]),
lc=f("skimlinks_excluded_classes",[]),mc=f("skimlinks_exclude",[]),nc=f("skimlinks_include",[]),oc=f("skimlinks_included_ids",[]),Va=f("skimlinks_exrel",""),Y=f("skimlinks_byrel",!1),Ab=f("skimlinks_ignore_hidden_links",false),$b=f("skimlinks_link_impression_exclude_selector",[]),
Mb=f("skimlinks_add_nofollow",false),Ib=f("skimlinks_before_click_handler",false,function(a,b){return oa(a)?a:b}),Bb=f("skimlinks_first_party_na",!1),yd=f("skimlinks_cookie_sync_optout",!0),bc=!f("noimpressions",!1),vb=f("skimlinks_replace_timeout",300,function(a,b){var c=parseFloat(a);return isNaN(c)?b:c}),Na=f("skimlinks_affiliate_unknown_links",true),
aa=f("skimlinks_target",null),zd=f("skimlinks_ajax_rerun",false),ea=f("sl_test",!1),F=[],sa=f("skimlinks_revenue_forecast",false),pc=f("skimlinks_noright",false),qc=f("skimlinks_url_extraction_rules",!1)||false,Wa=f("skimlinks_extra_redir_params",[]).join("&"),ia=f(["affiliate_tracking","skimlinks_tracking"],!1,function(a,b){var c=
/^[a-z0-9_\\|]+$/i;return a&&c.test(a)?a:b}),va=f("force_location"),D=f(["skimlinks_site","skimlinks_sitename"],!1),rc=f("skimlinks_domain","wordpress.redirectingat.com"),Ha=rc?"http://"+rc:"",R=f("skimlinks_google",false,function(a,b){return a?oa(a)?a?"skimout":"":y(a):b?"skimout":""}),ec=f("noskim_domains",[]),Ad=f("skimwords_horizontal_distance",80),Bd=f("skimwords_vertical_distance",80),
za=f("skimwords_color",null),Aa=f("skimwords_weight",null),Q=f("skimwords_decoration",null),Ba=f("skimwords_style",null),Ca=f("skimwords_title",null),Xa=f("no_skim_selector",""),od={SW_STANDARD:ud,SW_LITE:vd,SW_DIY:wd,SW_DIY_FILTER:xd,HAS_SKIMLINKS:ic,HAS_SKIMWORDS:jc,HAS_UNLINKED:kc,DO_NOT_TRACK:L,NO_COOKIE:V,SL_INCLUDED_CLASSES:S,
SL_EXCLUDED_CLASSES:lc,SL_EXCLUDED_DOMAINS:mc,SL_INCLUDED_DOMAINS:nc,SL_INCLUDED_IDS:oc,SL_EXCLUDED_REL:Va,SL_INCLUDED_REL:Y,SL_IGNORE_HIDDEN_LINKS:Ab,SL_IMPRESSION_EXCLUDED_SELECTORS:$b,SL_ADD_NOFOLLOW:Mb,SL_BEFORE_CLICK_HANDLER:Ib,SL_FIRST_PARTY_NA:Bb,SL_COOKIE_SYNC_OPTOUT:yd,SL_TRACK_IMPRESSION:bc,SL_REPLACE_TIMEOUT:vb,SL_AFFILIATE_UNKNOWN_LINKS:Na,SL_TARGET:aa,AJAX_SUPPORT:zd,SL_TEST:ea,UNLINKED_EXCLUDES:F,SL_FORECAST:sa,NO_RIGHT_CLICK:pc,USE_MERCHANT_URL_EXTRACTION_RULES:qc,EXTRA_REDIR_PARAMS:Wa,
CUSTOM_TRACKING_VAR:ia,FORCE_LOCATION:va,SITE_NAME:D,CUSTOM_WAYPOINT_DOMAIN:Ha,GOOGLE_TRACKING_ACTION_NAME:R,NO_SKIM_DOMAINS:ec,SW_HORIZONTAL_DISTANCE:Ad,SW_VERTICAL_DISTANCE:Bd,SL_PROFILING:!1,SW_LINK_COLOR:za,SW_LINK_WEIGHT:Aa,SW_LINK_DECORATION:Q,SW_LINK_STYLE:Ba,SW_LINK_TITLE:Ca,NO_SKIM_SELECTOR:Xa,SL_CONSENT:"ae",M101_TRACKING_ID:null},Cd="13.7.1",Dd="https://s.skimresources.com/js/GDPR",Ed="*.g.doubleclick.net *mjxads.internet.com *pgpartner.co.uk *pgpartner.com *pricegrabber.co.uk *pricegrabber.com *overture.com *youtube.com m.skimresources.com paid.outbrain.com trc.taboola.com traffic.outbrain.com zergnet.com *.criteo.com track.celtra.com".split(" "),
Fd=["noskim","norewrite"],Ma={"t.umblr.com":{name:"z"}},N="725X1342",dd="725",cd="1342",Zb={getItem:function(a){try{return JSON.parse(localStorage.getItem(a))}catch(b){return null}},setItem:function(a,b){try{localStorage.setItem(a,JSON.stringify(b))}catch(c){}}},h=function(){var a=p.referrer||document.referrer||"",b=va||l.location.href;var c="aspsession-id aspsessionid cftoken j-sessionid jsessid jsession_id jsessionid phpsessid phpsession-id phpsessionid seskey sessid session-id session-key session_id sessionid sessionkey uniqueid utm_campaign utm_medium utm_source utm_term".split(" ");
for(var d=0;d<c.length;d++){var e=c[d];var k=b.split("?");if(2<=k.length){b=k.shift();k=k.join("?");e=l.encodeURIComponent(e)+"=";k=k.split(/[&;]/gi);for(var g=k.length-1;0<=g;g--)Hc(k[g],e)&&k.splice(g,1);b=b+"?"+k.join("&")}}"?"===b[b.length-1]&&(b=b.substr(0,b.length-1));c=b;d=Zb.getItem("skimCONSENT");b=navigator.userAgent.toLowerCase();b=/(webkit)[ /]([\w.]+)/.exec(b)||/(opera)(?:.*version)?[ /]([\w.]+)/.exec(b)||/(msie) ([\w.]+)/.exec(b)||0>b.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(b)||
[];b={browser:b[1]||"",version:parseFloat(b[2])||0};e=(new Date).getTimezoneOffset();k="";for(g=0;8>g;g++)k+=Math.floor(65536*(1+Math.random())).toString(16).substring(1);return{cookie:"",country:"",locale:"",consent:d,detect:b,isAdblockUser:!1,pageLocation:c,referrer:a,sessid:"",timezone:e,uuid:k,skimwordsEnabled:jc,skimlinksEnabled:ic,unlinkedEnabled:kc}}(),m=function(){var a=document.getElementsByTagName("html")?document.getElementsByTagName("html")[0]:null,b=va?pa(va,!1):l.location.hostname;return{aff_domains:{},
beacon:[],domain_data:{domains:[]},exclude:mc,exclude_lookup:null,excluded_classes:["noskimlinks","noskim"].concat(lc),handlers:0,has_been_called:!1,hostname:b,html_root:a,include:nc,include_lookup:null,included_classes:S,included_ids:oc,links:[],links_tracked:!1,target:null,waypointDomain:tb()}}(),Zc={branded_merchant:!1,branded_merchant_url:!1,data:void 0,debug:0,force_country:!1,force_domain_check:!1,force_tree:!1,handler_attached_hook:!1,handlers:0,hover_name:"dark",link_all:!1,lite:!1,maxproducts:3,
merchant_excludes:!1,merchant_includes:!1,no_limit:!1,noVisual:!1,original_request:void 0,prio_threshold:0,request_counter:0,settings:null,send_in_progress:!1,x_min_visual_distance:80,y_min_visual_distance:80},ua={creative:"500005",url_spans:[]},t={topics:{},on:function(a,b,c){T(this.topics[a])||(this.topics[a]=[]);var d=void 0;c&&(d=function(a){Jc(a,c)&&b(a)});this.topics[a].push(d||b)},publish:function(a,b){w(this.topics[a]||[],function(a){n(a)&&a(b)})}},yb=p.getElementsByTagName("head")[0],Ea=
void 0,La=void 0,Sa=void 0,lb=void 0,jb={}.hasOwnProperty,Gd=[].indexOf;Ea=function(){var a;m.exclude_lookup={};m.include_lookup={};D&&m.exclude.push(D);var b=m.exclude.concat(Ed);var c=0;for(a=b.length;c<a;c++){var d=b[c];m.exclude_lookup[d]=d.length}b=m.include;c=0;for(a=b.length;c<a;c++)d=b[c],m.include_lookup[d]=d.length;return m.exclude_lookup};lb=function(a){var b=void 0;null!==m.exclude_lookup&&null!==m.include_lookup||Ea();if(!a)return!1;if(0===m.include.length)return!0;var c=m.include_lookup;
for(b in c)if(jb.call(c,b)){var d="*"===b.substr(0,1);var e="*"===b.substr(b.length-1,1);b=b.replace(/\*/g,"");if(d&&e){if(-1!==a.indexOf(b))return!0}else if(d){if(-1!==a.indexOf(b)&&a.indexOf(b)===a.length-b.length)return!0}else if(e){if(0===a.indexOf(b))return!0}else if(a===b)return!0}return!1};Sa=function(a){return!0===m.aff_domains[a]||(null===m.aff_domains[a]||void 0===m.aff_domains[a])&&Na&&!qa(a)};La=function(a){var b;if(!a)return!1;var c=a.toLowerCase().split(/\s+/);a=Va?[Va.toLowerCase()]:
[];a=a.concat(Fd);var d=0;for(b=c.length;d<b;d++){var e=c[d];if(0<=Gd.call(a,e))return!0}return!1};var z={AFFILIATE:"AFFILIATE",PRE_AFFILIATED:"PRE_AFFILIATED",UNKNOWN:"UNKNOWN",TRACK:"TRACK",IGNORE:"IGNORE"},Oc={async:!0,onError:function(){},onLoad:function(){}},Z=window.top,Eb={},Hd="AT BE BG CY DE ES FR GB GR IE IT LU MT NL PL PT SK".split(" "),Jb=ra(function(){if("msie"===h.detect.browser&&8>=h.detect.version)return!1;if(rb("skimlinks_force_consent"))return!0;var a=oa(h.consent);var b=h.country;
b=!!b&&v(Hd,b.toUpperCase());return!a&&b}),sc=[{id:1,moduleName:"ConsentA",getUrl:function(a,b){return function(c){c=v(b,c)?c:"en";return Dd+"/Consent_"+a+"_"+c+".js"}}("A",["bg","de","el","en","es","fr","it","pl","pt","sk"])}],ta=ra(function(){return sc[Math.floor(sc.length*Math.random())]}),M=void 0,gb=void 0,fb=void 0;fb=function(a){var b=void 0;if(qc){var c=H(a.hostname);if(c in Ma)return c="[&?]"+Ma[c].name+"=(http[^&]+)",c=new RegExp(c),decodeURIComponent(null!=(b=a.href)?b.match(c).pop():void 0)||a.href}return a.href};
gb=function(a,b){var c=h.referrer?"&pref="+x(h.referrer):"";var d=!1;if(0<b.indexOf("#slm-")){var e=b.split("#slm-");2!==e.length||isNaN(e[1])||10*parseInt(e[1],10)!==10*e[1]||(b=e[0],d=e[1])}var k=q(a,"data-skimlinks-tracking")||ia;var g=q(a,"data-skimlinks-editor")&&1===parseInt(q(a,"data-skimlinks-editor"),10)?1:0;if(A(a,"skimwords-link")){var f=q(a,"data-skimwords-word");e=q(a,"data-skim-creative");var O=q(a,"data-skim-product");var r=m.waypointDomain;b=r+"/?id="+N+(k?"&xcust="+k:"")+(!1!==d?
"&xs=9":"&xs=2")+"&url="+x(b)+"&xguid="+h.cookie+"&xuuid="+h.uuid+"&xsessid="+h.sessid+"&isjs=1&xword="+(f?f:"")+"&xcreo="+(e?e:"")+"&xpid="+(O?O:"")+"&xed="+g+"&sref="+x(l.location)+c+(L?"&dnt=1":"")+(V?"&fdnt=1":"")+(!1!==d?"&slmcid="+d:"")+(!1!==h.timezone?"&xtz="+h.timezone:"")}else A(a,"skimlinks-inline")?(e=q(a,"data-skim-creative"),b=m.waypointDomain+"/?id="+N+(D?"&site="+D:"")+(ea?"&test="+ea:"")+(k?"&xcust="+k:"")+(!1!==d?"&xs=9":"&xs=8")+"&isjs=1&url="+x(b)+"&xguid="+h.cookie+"&xuuid="+
h.uuid+"&xsessid="+h.sessid+"&xcreo="+(a&&null!=e?e:0)+"&xed="+g+"&sref="+x(l.location)+"&pref="+x(h.referrer)+(L?"&dnt=1":"")+(V?"&fdnt=1":"")+(!1!==d?"&slmcid="+d:"")+(!1!==h.timezone?"&xtz="+h.timezone:"")):J(a,"noskimlinks")||(e=q(a,"data-skim-creative"),b=m.waypointDomain+"/?id="+N+(D?"&site="+D:"")+(ea?"&test="+ea:"")+(k?"&xcust="+k:"")+(!1!==d?"&xs=9":"&xs=1")+"&isjs=1&url="+x(b)+"&xguid="+h.cookie+"&xuuid="+h.uuid+"&xsessid="+h.sessid+"&xcreo="+(a&&null!=e?e:0)+"&xed="+g+"&sref="+x(l.location)+
c+(L?"&dnt=1":"")+(V?"&fdnt=1":"")+(!1!==d?"&slmcid="+d:"")+(!1!==h.timezone?"&xtz="+h.timezone:""));0<Wa.length&&(b+="&"+Wa);h.isAdblockUser&&!J(a,"noskimlinks")&&(b+="&abp=1");b+="&jv="+Cd;return b+"&bv=2.5.1"};var Lb=void 0;Lb=function(a){var b,c=void 0;var d=f("skimlinks_strip_attribute",!1);if(!d)return!1;for(c in d)if(C(d,c)){var e=d[c];(b=q(a,c))&&0===b.indexOf(e)&&(b=b.substr(e.length),q(a,c,b))}return!0};var bb=function(){var a=/[-[\]{}()*+?.,\\^$|#]/g,b=/\s+/g;return function(c){return c.replace(a,
"\\$&").replace(b,"\\s+")}}();t.on("skim_js_init",function(){h.skimlinksEnabled&&(t.on("skim_js_start",Vc),t.on("EVENTS__BEACON_CALLBACK",Uc))});var Vb=void 0,wa=void 0,tc=void 0,uc=void 0,vc=void 0,wc=void 0,xc=void 0,ja=void 0,yc=void 0,fa=void 0,ha=void 0,zc={}.hasOwnProperty;ha=!1;fa={};vc=function(a){fa[a]=fa[a]||0;fa[a]++;return a+"_"+fa[a]};wa=function(a){var b;var c=b=null;if(-1!==a.indexOf(".")){a=a.split(".");var d=a[0];c=a[1]}else-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],c=
a[1].split("]"),c=c[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],b=a[1].split("]"),b=b[0]):d=a;return{tag:d,id:b,"class":c}};ja=function(a,b){var c;var d=b.split(",");var e=0;for(c=d.length;e<c;e++){b=d[e];b=y(b);b=wa(b);var k=!0;var g=(g="string"===typeof a.className?a.className:"")||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";var f=("function"===typeof a.getAttribute?a.getAttribute("id"):
void 0)||"";!b.tag||a.nodeName&&a.nodeName.toLowerCase()===b.tag||(k=!1);b["class"]&&(!g||g!==b["class"]&&0!==g.indexOf(b["class"]))&&(k=!1);b.id&&(!f||f!==b.id&&-1===f.indexOf(b.id))&&(k=!1);if(k)return!0}return!1};uc=function(a){var b,c;if("undefined"!==typeof document.querySelectorAll)return document.querySelectorAll(a);var d=[];a=wa(a);if(a.tag&&a["class"]){var e=document.getElementsByTagName(a.tag);var k=0;for(b=e.length;k<b;k++){var g=e[k];(c=g.className||g.getAttribute("class"))&&0===c.indexOf(a["class"])&&
d.push(g)}}else a.tag&&a.id?(g=document.getElementById(a.id))&&g.nodeName.toLowerCase()===a.tag&&d.push(g):(a=a.tag,d=document.getElementsByTagName(a));return d};wc=function(a,b,c){var d,e;var k=[];if("undefined"!==typeof a.querySelectorAll)k=a.querySelectorAll(b);else if(b=wa(b),b.tag&&b["class"]){if(!a.getElementsByTagName)return c?[]:!1;var g=a.getElementsByTagName(b.tag);var f=0;for(d=g.length;f<d;f++)if(a=g[f],(e=a.className||a.getAttribute("class"))&&0===e.indexOf(b["class"]))if(c)k.push(a);
else return!0}else if(b.tag&&b.id){if((a=document.getElementById(b.id))&&a.nodeName&&a.nodeName.toLowerCase()===b.tag)if(c)k.push(a);else return!0}else b=b.tag,k=a.getElementsByTagName(b);return c?k:0<k.length};xc=function(a){var b=a.offsetWidth;a=a.offsetHeight;return 468===b&&60===a||234===b&&60===a||728===b&&90===a||300===b&&250===a||250===b&&250===a||336===b&&280===a||160===b&&600===a||120===b&&600===a?!0:!1};tc=function(){var a=[];a.push("div.widget-content");a.push("div.googleAdText");a.push("div[id=ad]");
a.push("div[id=banner]");a.push("div[id=advertisement]");a.push("div[id=adv_container]");a.push("div.ad");a.push("div.banner");a.push("div.advertisement");a.push("div.ad_container");a.push("span.IL_AD");a.push("div[id=fave-ext-container]");a.push("span.skimlinks-unlinked");-1!==l.location.href.indexOf(".google.")?(a.push("td.gac_c"),a.push("table[id=mbEnd]"),a.push("div[id=mbEnd]"),a.push("span[id=taw]"),a.push("td.std"),a.push("div.std"),a.push("table.gssb_e"),a.push("div.c"),a.push("div[id=tads]")):
-1!==l.location.href.indexOf(".yahoo.")?(a.push("ul.spns,ul.reducepx-spnslist"),a.push("ul[class*=reducepx-spnslist]"),a.push("ul[id=east]")):-1!==l.location.href.indexOf(".aol.")?(a.push("div.sllLink"),a.push("div.n")):-1!==l.location.href.indexOf(".bing.")&&(a.push("div.sb_adsW"),a.push("div[id=sidebar]"),a.push("div.sb_adsWv2"),a.push("div.sb_adsNv2"),a.push("div[class*=sb_ads]"));return a};yc=function(a){var b;var c={};var d=0;for(b=a.length;d<b;d++){var e=a[d];c[e]=!0}return c};var G=function(){var a=
void 0;a={};return{traverse:function(b,c,d,e){b=b||[];c=c||[];d=d||[];return a&&a.length&&!e?a:this.traverse_dom(b,c,d)},traverse_dom:function(b,c,d){var e,k;if(ha)return a;ha=!0;var g=this.get_exclude_selector(c);var f=this.get_exclude_selector([]);c=g.selector;g=g.needed;f=f.selector;0===b.length&&b.push("body");b=b.concat(d);for(var h=0,m=b.length;h<m;h++){var l=b[h];l=Nb(l);l=uc(l);var q=e=0;for(k=l.length;e<k;q=++e)q=l[q],this.traverse_node(q,g,f,c,d)}return a},traverse_node:function(b,c,d,e,
k){var g=[];var f=0;for(g.push({node:b,tagName:"",readOnly:!1,parent_id:null});f<g.length;)!(b=g[f].node)||xc(b)||J(b,"noskimwords",!0)||c&&""!==d&&ja(b,d)||(g[f].readOnly=!1,b.nodeName&&"#text"!==b.nodeName?(g[f].tagName=b.nodeName,null!==g[f].parent_id&&(g[f].readOnly=g[g[f].parent_id].readOnly),g[f].readOnly||(c&&ja(b,e)?g[f].readOnly=!0:v(k,b.nodeName.toLowerCase())&&(g[f].readOnly=!0)),v(k,b.nodeName.toLowerCase())&&(g[f].readOnly=!0)):null!==g[f].parent_id&&(g[f].tagName=g[g[f].parent_id].tagName,
g[f].readOnly=g[g[f].parent_id].readOnly),"msie"===h.detect.browser&&9>h.detect.version&&g[f].readOnly||(b.hasChildNodes()?g=this.add_child_nodes(g[f],f,g):this._add(b,!1,g[f].tagName,g[f].readOnly))),f++;return a},is_traversed:function(){return ha},is_good_tag:function(a){return yc("p body div span ul ol li table tbody td tr th tfoot col colgroup em strong big small blockquote cite b dl dfn dd dt ins form legend noframes pre noscript center font i article section main".split(" "))[a.nodeName.toLowerCase()]?
!0:!1},is_html:function(a){return(a=y(a))&&"<"===a[0]},get_non_colliding_nodes:function(){var b=void 0;var c=a;var d={};for(b in c)zc.call(c,b)&&(d[b]=c[b]);return d},get_as_hash_node_dict:function(){var b=void 0;var c={};for(b in a){var d=a[b];C(a,b)&&(c[b]=d)}return c},get_as_pair_array:function(){var b=void 0;var c=[];for(b in a)zc.call(a,b)&&c.push([b,a[b]]);return c},get_exclude_selector:function(a,c){var b,e,f;var g=[];if(!c){c=document.getElementsByTagName("body");if(!c.length)return{needed:!1,
selector:""};c=c[0]}a=a.concat(tc());var h=b=0;for(e=a.length;b<e;h=++b)a[h]=Nb(a[h]);b=!1;e="";var m=0;for(f=a.length;m<f;m++)h=a[m],wc(c,h,!1)&&g.push(h);g.length&&(b=!0,e=g.join(",").replace("class=","class^="));return{needed:b,selector:e}},length:function(){return W(a).length},reset:function(){a=[];return ha=!1},add_child_nodes:function(a,c,d){var b,f;var g=a.node.childNodes;var h=0;for(f=g.length;h<f;h++)(b=g[h])&&b.nodeName&&!this._add(b,!1,a.tagName,a.readOnly)&&this.is_good_tag(b)&&d.push({node:b,
tagName:a.tagName,readOnly:a.readOnly,parent_id:c});return d},add_node:function(a,c){return this._add(a,c)},_add:function(b,c,d,e){var f=null;"#text"===b.nodeName&&(f=y(b.nodeValue));c=c||!1;if("msie"===h.detect.browser&&9>h.detect.version&&e)return!1;if("msie"!==h.detect.browser||9<=h.detect.version)try{b.meta={ElementTag:d,ReadOnly:e}}catch(g){}if(f&&!this.is_html(f)&&3<=f.length){if(c&&"-1"===c)return!1;c=this._skim_id_hash(f,c);if(!c)return!1;a[c]=b}return f?!0:!1},_skim_id_hash:function(a){if(!a)return"";
var b=y(a.replace(/\s+/g," ")).length;a=a.replace(/[:\s]*/g,"");b=b+":"+a.substring(0,20);return b=vc(b)}}}();Vb=function(a,b,c){if(sa)return!1;var d=(a.data?a.data:a.childNodes[0].data).replace(b.repl_regex,b.replacement);var e=document.createElement("span");b=document.createDocumentFragment();e.innerHTML=d;if("msie"===h.detect.browser&&9>h.detect.version){d=a.previousSibling;var f=/^\s/;d&&d.nodeValue&&d.nodeValue.length&&f.test(d.nodeValue[d.nodeValue.length-1])&&(d.nodeValue+=" ");(d=a.nextSibling)&&
d.nodeValue&&d.nodeValue.length&&f.test(d.nodeValue[0])&&(d.nodeValue=" "+d.nodeValue)}for(;e.firstChild;)"#text"===e.firstChild.nodeName?(d=b.appendChild(e.firstChild),G.add_node(d)):(d=b.appendChild(e.firstChild),null===d||c||ab(d,!0));if(c=a.parentNode)return c.replaceChild(b,a)};var E={called:!1,pendingRequests:0},u={campaign_ids:[],loading_started:(new Date).getTime(),linksImpressions:{skimlinks:{count:0,urls:{}},skimwords:{count:0,urls:{}},unlinked:{count:0,urls:{}}},awaitedModules:[]},Qb={post:function(a,
b,c,d){d=B({method:"POST"},d);Ob(a,b,c,d)},get:function(a,b,c,d){d=B({method:"GET"},d);Ob(a,b,c,d)}},Wb=void 0,Tb=void 0,Ac=void 0,Ub=void 0;Wb=function(a){Ia(a,"click",la);pc||Ia(a,"contextmenu",la);return ab(a,!1)};Ac=function(a,b,c,d){var e=bb(a);var f="";m.target&&(f='target="'+m.target+'"');b=Ra(b);e="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+e+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";a=x(Ra(a));b='$1$2<a href="'+b+'" class="'+d+'" '+f+' data-skimwords-word="'+a+
'"  data-skim-creative="'+c+'" title="">$3$4</a>$5$6';c=e.replace(/\?:/g,"");return{search_regex:new RegExp(e,"i"),repl_regex:new RegExp(c,"i"),repl_text:b}};Tb=function(a,b){var c,d,e=void 0,f;if(!a||$a(a,["span.skimlinks-unlinked"]))return[[],[]];var g=a.data;var m=[];var l=[];for(d=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi;c=d.exec(g);){var r=c[0];if("link.phrase"!==r){var u=c.index;if(0<y(r).length&&-1===r.indexOf("/.")&&-1===r.indexOf("...")){var n=
r;0!==r.indexOf("http")&&0!==r.indexOf("//")&&(n="msie"===h.detect.browser&&6>=h.detect.version?"http://"+r:"//"+r);c=pa(n);var t=Ec({OriginalPhrase:""+r,Url:n,Title:"",ActionType:2,GroupId:0,Unlinked:!0});(f=Ac(""+r,n,ua.creative,"skimlinks-unlinked"))&&l.push({start:u,text:""+Ra(r),domain:c,repl_regex:f.repl_regex,replacement:f.repl_text,regex:f.search_regex,phrase:t,link:n});m.push(c)}else break}}if(l.length){e=b;n="skimlinks-unlinked";var w;r=document.createDocumentFragment();var p=0;c=[];u=a.nodeValue;
d=[];g=a.parentNode;n||(n="skimwords-potential");e||(e="-1");if(g){t=0;for(w=l.length;t<w;t++){var v=l[t];var x=document.createElement("span");x.className=n;f=document.createTextNode(u.substring(p,v.start));r.appendChild(f);x.innerHTML=v.text;r.appendChild(x);p={};p.node=x;p.match=v;q(p,"occurrence",v.target_occurrence);c.push(p);p=v.start+v.text.length;d.push(f);G.add_node(f,e)}l=document.createTextNode(u.substring(p));d.push(l);r.appendChild(l);G.add_node(l,e);g.replaceChild(r,a)}e=[c,d];l=e[0];
e=e[1];r=0;for(d=l.length;r<d;r++)g=l[r],ua.url_spans.push(g)}e||(e=[]);return[m,e]};Ub=function(a){var b;if(m.exclude.length){var c=m.exclude;var d=0;for(b=c.length;d<b;d++){var e=c[d];if(e===a)return!1}}if(m.include.length){c=m.include;d=0;for(b=c.length;d<b;d++)if(e=c[d],e===a)return!0;return!1}return!0};t.on("skim_js_init",function(){l.__SKIM_JS_GLOBAL__.bundledEntries.unlinked=!0;if(h.unlinkedEnabled){if(h.skimwordsEnabled)t.on("instant_api_callback_settings",Yc);else t.on("EVENTS__BEACON_CALLBACK",
Rb,{type:"BEACON_CALLBACK__POST_PAGE_LOAD"});t.on("dom_changed",Sb);t.on("EVENTS__BEACON_CALLBACK",$c,{type:"BEACON_CALLBACK__AUX"})}});t.on("skim_js_init",function(){l.__SKIM_JS_GLOBAL__.bundledEntries.GDPRConsent=!0});t.on("EVENTS__BEACON_CALLBACK",function(a){if(a.isFirstCall){var b=ta();a=b.moduleName;b=b.getUrl;Jb()&&Pc(a,b(h.locale),fd)}});t.on("skim_js_init",function(){u.awaitedModules.push("main-tracking");h.skimwordsEnabled&&u.awaitedModules.push("skimwords");h.unlinkedEnabled&&u.awaitedModules.push("unlinked");
t.on("EVENTS__BEACON_CALLBACK",id,{type:"BEACON_CALLBACK__POST_PAGE_LOAD"})});var Ta=!1,P=!1,ba=null,ca=null,Id={detect:function(a){a:{try{var b=navigator.userAgent.toLowerCase();if(-1===b.indexOf("firefox")&&-1===b.indexOf("chrome")){P=!0;Ta=!1;break a}}catch(c){}b=""+11*Math.random();ba=new Image;ba.onload=dc;ba.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"1").replace(/\*/,b);ca=new Image;ca.onload=dc;ca.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"2").replace(/\*/,b)}cc(a,
250)}},qd={AT:"de",BE:"fr",BG:"bg",CY:"el",CZ:"cs",DE:"de",DK:"da",EE:"et",ES:"es",FI:"fi",FR:"fr",GB:"en",GR:"el",HR:"hr",HU:"hu",IE:"en",IT:"it",LT:"lt",LU:"fr",LV:"lv",MT:"en",NL:"en",PL:"pl",PT:"pt",RO:"ro",SE:"sv",SI:"sl",SK:"sk"},fc=0;l.skimlinksODPCallback=function(a){var b=a.status;a=a.actions;a=void 0===a?[]:a;b&&"OK"===b&&w(a,function(a){var b=a.url;"pixel"===a.action&&na(b)})};var Jd={skimlinks:!1,skimwords:!1,unlinked:!1,audience:!1,GDPRConsent:!1};(function(){if(ld()&&(l.__SKIM_JS_GLOBAL__||
(l.__SKIM_JS_GLOBAL__={}),!l.__SKIM_JS_GLOBAL__.init)){l.__SKIM_JS_GLOBAL__.init=!0;l.__SKIM_JS_GLOBAL__.getDebugInfo=nd;l.__SKIM_JS_GLOBAL__.bundledEntries=Jd;if(md(m.hostname)||Xa&&jd(Xa))h.skimlinksEnabled=!1,h.skimwordsEnabled=!1,h.unlinkedEnabled=!1;"msie"===h.detect.browser&&8>=h.detect.version&&(h.skimwordsEnabled=!1);Id.detect(function(a){h.isAdblockUser=a});t.publish("skim_js_init");n(l.skimlinksBeaconCallback)||(l.skimlinksBeaconCallback=Dc);n(l.skimlinksBeaconSecondaryCallback)||(l.skimlinksBeaconSecondaryCallback=
Cc);n(l.skimlinksBeaconAuxCallback)||(l.skimlinksBeaconAuxCallback=Bc);v(["interactive","complete"],p.readyState)?setTimeout(da,0):(gc("skimlinksBeaconCallback"),document.addEventListener("DOMContentLoaded",da),document.addEventListener("load",da));t.publish("skim_js_start")}})()})();
